# Generated by Django 4.1 on 2025-02-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guestapp', '0006_tbl_studio_simage'),
        ('Studioapp', '0006_alter_tbl_package_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requireddate', models.DateField()),
                ('noofdays', models.BigIntegerField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=25)),
                ('remark', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_customer')),
                ('packageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studioapp.tbl_package')),
            ],
        ),
    ]
