# Generated by Django 4.1 on 2025-02-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('iamount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tamount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=25)),
                ('paymentdate', models.DateField(auto_now_add=True)),
                ('requestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customerapp.tbl_request')),
            ],
        ),
    ]
