# Generated by Django 4.1 on 2025-02-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0002_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='camount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='noofdays',
            field=models.BigIntegerField(),
        ),
    ]
