# Generated by Django 4.1 on 2025-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0003_tbl_payment_camount_alter_tbl_request_noofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='aamount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
