# Generated by Django 4.1 on 2025-03-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0006_tbl_studio_simage'),
        ('Studioapp', '0007_tbl_work_workimg'),
        ('Customerapp', '0004_tbl_request_aamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_customer')),
                ('packageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studioapp.tbl_package')),
            ],
        ),
    ]
