# Generated by Django 4.1 on 2025-03-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0006_tbl_studio_simage'),
        ('Studioapp', '0007_tbl_work_workimg'),
        ('Customerapp', '0005_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Tbl_feedback',
        ),
    ]
