# Generated by Django 4.1 on 2025-01-13 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=25)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_district')),
            ],
        ),
    ]
