# Generated by Django 4.1 on 2025-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=25)),
                ('categoryimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
