# Generated by Django 4.1 on 2025-01-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0003_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_work',
            fields=[
                ('workid', models.AutoField(primary_key=True, serialize=False)),
                ('workname', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=400)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_category')),
            ],
        ),
    ]
