# Generated by Django 4.1 on 2025-01-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_workimage',
            fields=[
                ('workimageid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Studioapp.tbl_work')),
            ],
        ),
    ]
