# Generated by Django 4.1 on 2025-01-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studioapp', '0002_tbl_workimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_workimage',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='tbl_workimage',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_workimage',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_workimage',
            name='image4',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_workimage',
            name='image5',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='tbl_workimage',
            name='image6',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
