# Generated by Django 4.1 on 2025-01-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0005_rename_customrname_tbl_customer_customername'),
        ('Studioapp', '0003_rename_image_tbl_workimage_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_work',
            name='studioid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_studio'),
        ),
    ]
