# Generated by Django 4.1 on 2025-01-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_tbl_category'),
        ('Guestapp', '0005_rename_customrname_tbl_customer_customername'),
        ('Studioapp', '0004_tbl_work_studioid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_package',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('packagename', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_category')),
                ('studioid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_studio')),
            ],
        ),
    ]
