# Generated by Django 4.1 on 2025-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studioapp', '0005_tbl_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_package',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
