# Generated by Django 4.1 on 2025-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studioapp', '0006_alter_tbl_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_work',
            name='workimg',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
