# Generated by Django 4.1 on 2025-01-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_tbl_category'),
        ('Guestapp', '0003_tbl_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customrname', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_login')),
            ],
        ),
    ]
