# Generated by Django 4.1 on 2025-01-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0004_tbl_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='customrname',
            new_name='customername',
        ),
    ]
