# Generated by Django 4.1 on 2025-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0005_rename_customrname_tbl_customer_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_studio',
            name='simage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
